/*
 * Copyright 2013 National Bank of Belgium
 *
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved 
 * by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * 
 * http://ec.europa.eu/idabc/eupl
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and 
 * limitations under the Licence.
 */
package jdplus.benchmarking.desktop.plugin.benchmarking.ui;

import jdplus.benchmarking.desktop.plugin.benchmarking.documents.CubicSplineDocumentManager;
import jdplus.toolkit.desktop.plugin.ui.processing.Ts2ProcessingViewer;
import jdplus.toolkit.desktop.plugin.workspace.DocumentUIServices;
import jdplus.toolkit.desktop.plugin.workspace.WorkspaceFactory;
import jdplus.toolkit.desktop.plugin.workspace.WorkspaceItem;
import jdplus.toolkit.desktop.plugin.workspace.ui.WorkspaceTs2TopComponent;
import jdplus.benchmarking.base.core.benchmarking.univariate.CubicSplineDocument;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//jdplus.benchmarking.desktop.plugin.benchmarking.ui//CubicSpline//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "CubicSplineTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "jdplus.benchmarking.desktop.plugin.benchmarking.ui.CubicSpline")
@ActionReference(path = "Menu/Statistical methods/Benchmarking", position = 2500)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_CubicSplineAction")
@Messages({
    "CTL_CubicSplineAction=CubicSpline",
    "CTL_CubicSplineTopComponent=CubicSpline Window",
    "HINT_CubicSplineTopComponent=This is a CubicSpline window"
})
public final class CubicSplineTopComponent extends WorkspaceTs2TopComponent<CubicSplineDocument> {

    private final ExplorerManager mgr = new ExplorerManager();

    private static CubicSplineDocumentManager manager() {
        return WorkspaceFactory.getInstance().getManager(CubicSplineDocumentManager.class);
    }

    public CubicSplineTopComponent() {
        this(null);
    }

    public CubicSplineTopComponent(WorkspaceItem<CubicSplineDocument> doc) {
        super(doc);
        initComponents();
        setToolTipText(Bundle.CTL_CubicSplineTopComponent());
    }

    @Override
    protected Ts2ProcessingViewer initViewer() {
        //       node=new InternalNode();
        return Ts2ProcessingViewer.create(this.getElement(), DocumentUIServices.forDocument(CubicSplineDocument.class), "Low-freq series", "High-freq series");
    }

    @Override
    public WorkspaceItem<CubicSplineDocument> newDocument() {
        return manager().create(WorkspaceFactory.getInstance().getActiveWorkspace());
    }

    //    private UniCubicSplineSpecification getSpecification(){
//        return getDocument().getElement().getSpecification();
//    }
//
//    private void setSpecification(UniCubicSplineSpecification spec){
//        getDocument().getElement().setSpecification(spec);
//        updateView();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String getContextPath() {
        return CubicSplineDocumentManager.CONTEXTPATH; //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }

}
